dist: bionic
language: python
python:
  - "3.10"

services:
  - docker

jobs:
  include:
    - stage: Linting
      script:
        - pip install black isort flake8
        - black . --check
        - isort . --check
        - flake8 .
    - stage: Test
      script:
        - pip install -r requirements.txt
        - pytest src/tests
